/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store a newly created resource in storage. */
        post: operations["storeANewlyCreatedResourceInStorage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 儲存新建立的分類資源
         * @description 使用 StoreCategoryRequest 進行數據驗證，確保：
         *     - 分類名稱必填且不超過255字符
         *     - 父分類ID必須存在於資料表中
         *     - 描述為可選欄位
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Must not be greater than 255 characters.
                         * @example vmqeopfuudtdsufvyvddq
                         */
                        name: string;
                        /** @example Dolores dolorum amet iste laborum eius est dolor. */
                        description?: string | null;
                        /**
                         * @description The <code>id</code> of an existing record in the categories table.
                         * @example 17
                         */
                        parent_id?: number | null;
                    };
                };
            };
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the category.
                 * @example 17
                 */
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * 更新指定的分類資源
         * @description 使用 UpdateCategoryRequest 進行數據驗證，包含：
         *     - 部分更新支援（sometimes 規則）
         *     - 防止自我循環的業務邏輯保護
         *     - 確保父分類存在性檢查
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The ID of the category.
                     * @example 17
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Must not be greater than 255 characters.
                         * @example vmqeopfuudtdsufvyvddq
                         */
                        name: string;
                        /** @example Dolores dolorum amet iste laborum eius est dolor. */
                        description?: string | null;
                        /**
                         * @description The <code>id</code> of an existing record in the categories table.
                         * @example 17
                         */
                        parent_id?: number | null;
                    };
                };
            };
            responses: never;
        };
        post?: never;
        /**
         * 刪除指定的分類資源
         * @description 執行軟刪除操作，根據資料表外鍵約束設定：
         *     - 當分類被刪除時，其子分類也會被級聯刪除
         *     - 關聯的商品 category_id 會被設為 null
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The ID of the category.
                     * @example 17
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the store.
                 * @example 17
                 */
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteApiStoresId"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 獲取所有屬性列表
         * @description 返回系統中所有的商品屬性，包含其相關的屬性值
         *     使用 Eager Loading 避免 N+1 查詢問題
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        /**
         * 創建新屬性
         * @description 創建一個新的商品屬性，屬性名稱必須唯一
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 屬性名稱，例如：顏色、尺寸、材質
                         * @example 顏色
                         */
                        name: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attributes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the attribute.
                 * @example 17
                 */
                id: number;
                /**
                 * @description 屬性 ID
                 * @example 1
                 */
                attribute: number;
            };
            cookie?: never;
        };
        /**
         * 獲取指定屬性
         * @description 返回指定的商品屬性詳細資訊，包含其所有屬性值
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The ID of the attribute.
                     * @example 17
                     */
                    id: number;
                    /**
                     * @description 屬性 ID
                     * @example 1
                     */
                    attribute: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        /**
         * 更新指定屬性
         * @description 更新指定的商品屬性，屬性名稱必須唯一（忽略當前屬性）
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The ID of the attribute.
                     * @example 17
                     */
                    id: number;
                    /**
                     * @description 屬性 ID
                     * @example 1
                     */
                    attribute: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 屬性名稱
                         * @example 顏色
                         */
                        name: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        post?: never;
        /**
         * 刪除指定屬性
         * @description 刪除指定的商品屬性及其所有相關的屬性值
         *     注意：如果有商品變體正在使用此屬性的值，刪除操作可能會失敗
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The ID of the attribute.
                     * @example 17
                     */
                    id: number;
                    /**
                     * @description 屬性 ID
                     * @example 1
                     */
                    attribute: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 批量刪除商品
         * @description 根據提供的商品 ID 陣列批量刪除商品。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 要刪除的商品 ID 陣列。
                         * @example [
                         *       1,
                         *       2,
                         *       3
                         *     ]
                         */
                        ids: number[];
                    };
                };
            };
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 顯示所有商品列表，支援分頁、排序和篩選功能 */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description 頁碼，預設為 1。
                     * @example 1
                     */
                    page?: number;
                    /**
                     * @description 每頁項目數，預設為 15。
                     * @example 15
                     */
                    per_page?: number;
                    /**
                     * @description 搜尋商品名稱或 SKU。
                     * @example 椅子
                     */
                    search?: string;
                    /**
                     * @description 排序欄位 (name, sku, selling_price, cost_price, created_at)。
                     * @example selling_price
                     */
                    sort_by?: string;
                    /**
                     * @description 排序方向 (asc, desc)，預設為 asc。
                     * @example desc
                     */
                    sort_order?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 商品列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example [
                             *       {
                             *         "id": 1,
                             *         "name": "高階人體工學辦公椅",
                             *         "sku": "CHAIR-ERG-001",
                             *         "description": "具備可調節腰靠和 4D 扶手，提供全天候舒適支撐。",
                             *         "selling_price": 399.99,
                             *         "cost_price": 150,
                             *         "category_id": 1,
                             *         "created_at": "2024-01-01T10:00:00.000000Z",
                             *         "updated_at": "2024-01-01T10:00:00.000000Z"
                             *       },
                             *       {
                             *         "id": 2,
                             *         "name": "無線藍牙滑鼠",
                             *         "sku": "MOUSE-BT-002",
                             *         "description": "2.4GHz 無線連接，DPI 可調，適合辦公和遊戲。",
                             *         "selling_price": 79.99,
                             *         "cost_price": 25,
                             *         "category_id": null,
                             *         "created_at": "2024-01-01T11:30:00.000000Z",
                             *         "updated_at": "2024-01-01T11:30:00.000000Z"
                             *       }
                             *     ] */
                            data?: {
                                /** @example 1 */
                                id?: number;
                                /** @example 高階人體工學辦公椅 */
                                name?: string;
                                /** @example CHAIR-ERG-001 */
                                sku?: string;
                                /** @example 具備可調節腰靠和 4D 扶手，提供全天候舒適支撐。 */
                                description?: string;
                                /** @example 399.99 */
                                selling_price?: number;
                                /** @example 150 */
                                cost_price?: number;
                                /** @example 1 */
                                category_id?: number;
                                /** @example 2024-01-01T10:00:00.000000Z */
                                created_at?: string;
                                /** @example 2024-01-01T10:00:00.000000Z */
                                updated_at?: string;
                            }[];
                            meta?: {
                                /** @example 1 */
                                current_page?: number;
                                /** @example 1 */
                                from?: number;
                                /** @example 3 */
                                last_page?: number;
                                /** @example 15 */
                                per_page?: number;
                                /** @example 2 */
                                to?: number;
                                /** @example 45 */
                                total?: number;
                            };
                            links?: {
                                /** @example http://localhost/api/products?page=1 */
                                first?: string;
                                /** @example http://localhost/api/products?page=3 */
                                last?: string;
                                /** @example null */
                                prev?: string;
                                /** @example http://localhost/api/products?page=2 */
                                next?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** 建立新商品 (SPU/SKU) */
        post: operations["SPUSKU"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 商品的 ID。
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        /** 顯示指定的商品 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 商品的 ID。
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 商品詳細資料 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** @example 1 */
                                id?: number;
                                /** @example 高階人體工學辦公椅 */
                                name?: string;
                                /** @example CHAIR-ERG-001 */
                                sku?: string;
                                /** @example 具備可調節腰靠和 4D 扶手。 */
                                description?: string;
                                /** @example 399.99 */
                                selling_price?: number;
                                /** @example 150 */
                                cost_price?: number;
                                /** @example 1 */
                                category_id?: number;
                                /** @example 2024-01-01T10:00:00.000000Z */
                                created_at?: string;
                                /** @example 2024-01-01T10:00:00.000000Z */
                                updated_at?: string;
                            };
                        };
                    };
                };
            };
        };
        /** 更新指定的商品 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 商品的 ID。
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 商品的完整名稱。
                         * @example 高階人體工學辦公椅
                         */
                        name: string;
                        /**
                         * @description 商品的唯一庫存單位編號 (SKU)。
                         * @example CHAIR-ERG-001
                         */
                        sku: string;
                        /**
                         * @description 商品的詳細描述。
                         * @example 具備可調節腰靠和 4D 扶手。
                         */
                        description?: string | null;
                        /**
                         * @description 商品的銷售價格。
                         * @example 399.99
                         */
                        selling_price: number;
                        /**
                         * @description 商品的成本價格。
                         * @example 150
                         */
                        cost_price: number;
                        /**
                         * @description 商品所屬分類的 ID。可為空值表示不屬於任何分類。
                         * @example 1
                         */
                        category_id?: number | null;
                    };
                };
            };
            responses: {
                /** @description 商品更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** @example 1 */
                                id?: number;
                                /** @example 高階人體工學辦公椅 */
                                name?: string;
                                /** @example CHAIR-ERG-001 */
                                sku?: string;
                                /** @example 具備可調節腰靠和 4D 扶手。 */
                                description?: string;
                                /** @example 399.99 */
                                selling_price?: number;
                                /** @example 150 */
                                cost_price?: number;
                                /** @example 1 */
                                category_id?: number;
                                /** @example 2024-01-01T10:00:00.000000Z */
                                created_at?: string;
                                /** @example 2024-01-01T10:00:00.000000Z */
                                updated_at?: string;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        /** 刪除指定的商品 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description 商品的 ID。
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 商品刪除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attributes/{attribute_id}/values": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the attribute.
                 * @example 17
                 */
                attribute_id: number;
                /**
                 * @description 屬性 ID
                 * @example 1
                 */
                attribute: number;
            };
            cookie?: never;
        };
        /**
         * 獲取指定屬性的所有值
         * @description 返回指定屬性下的所有屬性值列表
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The ID of the attribute.
                     * @example 17
                     */
                    attribute_id: number;
                    /**
                     * @description 屬性 ID
                     * @example 1
                     */
                    attribute: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        /**
         * 為指定屬性創建新值
         * @description 在指定屬性下創建一個新的屬性值
         *     屬性值在同一屬性下必須唯一
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The ID of the attribute.
                     * @example 17
                     */
                    attribute_id: number;
                    /**
                     * @description 屬性 ID
                     * @example 1
                     */
                    attribute: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 屬性值，例如：紅色、藍色、S、M、L
                         * @example 紅色
                         */
                        value: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/values/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the value.
                 * @example 17
                 */
                id: number;
                /**
                 * @description 屬性值 ID
                 * @example 1
                 */
                value: number;
            };
            cookie?: never;
        };
        /**
         * 獲取指定屬性值
         * @description 返回指定的屬性值詳細資訊
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The ID of the value.
                     * @example 17
                     */
                    id: number;
                    /**
                     * @description 屬性值 ID
                     * @example 1
                     */
                    value: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        /** 更新指定的屬性值 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The ID of the value.
                     * @example 17
                     */
                    id: number;
                    /**
                     * @description 屬性值 ID
                     * @example 1
                     */
                    value: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 新的屬性值。
                         * @example "深藍色"
                         */
                        value: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** @example 1 */
                                id?: number;
                                /** @example 紅色 */
                                value?: string;
                                /** @example 1 */
                                attribute_id?: number;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        /**
         * 刪除指定屬性值
         * @description 刪除指定的屬性值
         *     注意：如果有商品變體正在使用此屬性值，刪除操作可能會失敗
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The ID of the value.
                     * @example 17
                     */
                    id: number;
                    /**
                     * @description 屬性值 ID
                     * @example 1
                     */
                    value: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 顯示用戶列表
         * @description 支援對 name 和 username 欄位進行部分匹配篩選。
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description 對用戶名稱進行模糊搜尋。
                     * @example admin
                     */
                    "filter[name]"?: string;
                    /**
                     * @description 對用戶帳號進行模糊搜尋。
                     * @example superadmin
                     */
                    "filter[username]"?: string;
                    /**
                     * @description 對名稱或帳號進行全域模糊搜尋。
                     * @example admin
                     */
                    "filter[search]"?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example [
                             *       {
                             *         "id": 1,
                             *         "name": "Super Admin",
                             *         "username": "superadmin",
                             *         "role": "admin",
                             *         "role_display": "管理員",
                             *         "is_admin": true,
                             *         "created_at": "2025-06-11T10:00:00.000000Z",
                             *         "updated_at": "2025-06-11T10:00:00.000000Z"
                             *       }
                             *     ] */
                            data?: {
                                /** @example 1 */
                                id?: number;
                                /** @example Super Admin */
                                name?: string;
                                /** @example superadmin */
                                username?: string;
                                /** @example admin */
                                role?: string;
                                /** @example 管理員 */
                                role_display?: string;
                                /** @example true */
                                is_admin?: boolean;
                                /** @example 2025-06-11T10:00:00.000000Z */
                                created_at?: string;
                                /** @example 2025-06-11T10:00:00.000000Z */
                                updated_at?: string;
                            }[];
                            links?: {
                                /** @example http://localhost/api/users?page=1 */
                                first?: string;
                                /** @example http://localhost/api/users?page=1 */
                                last?: string;
                                /** @example null */
                                prev?: string;
                                /** @example null */
                                next?: string;
                            };
                            meta?: {
                                /** @example 1 */
                                current_page?: number;
                                /** @example 1 */
                                from?: number;
                                /** @example 1 */
                                last_page?: number;
                                /** @example http://localhost/api/users */
                                path?: string;
                                /** @example 15 */
                                per_page?: number;
                                /** @example 1 */
                                to?: number;
                                /** @example 1 */
                                total?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 建立新用戶
         * @description 接收用戶創建請求，進行驗證後建立新用戶帳號。
         *     自動將密碼進行 bcrypt 雜湊處理確保安全性。
         *     權限檢查：需要通過 UserPolicy::create() 方法（僅管理員可執行）
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Must not be greater than 255 characters.
                         * @example vmqeopfuudtdsufvyvddq
                         */
                        name: string;
                        /**
                         * @description Must not be greater than 255 characters.
                         * @example amniihfqcoynlazghdtqt
                         */
                        username: string;
                        /**
                         * @description Must be at least 8 characters.
                         * @example t(!Cs'YAKYLk4>S
                         */
                        password: string;
                        /**
                         * @example admin
                         * @enum {string}
                         */
                        role: "admin" | "viewer";
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** @example 1 */
                                id?: number;
                                /** @example Super Admin */
                                name?: string;
                                /** @example superadmin */
                                username?: string;
                                /** @example admin */
                                role?: string;
                                /** @example 管理員 */
                                role_display?: string;
                                /** @example true */
                                is_admin?: boolean;
                                /** @example 2025-06-11T10:00:00.000000Z */
                                created_at?: string;
                                /** @example 2025-06-11T10:00:00.000000Z */
                                updated_at?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the user.
                 * @example 17
                 */
                id: number;
                /**
                 * @description 用戶的 ID。
                 * @example 1
                 */
                user: number;
            };
            cookie?: never;
        };
        /**
         * 顯示指定用戶
         * @description 根據用戶 ID 返回特定用戶的完整資料。
         *     權限檢查：需要通過 UserPolicy::view() 方法（僅管理員可存取）
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The ID of the user.
                     * @example 17
                     */
                    id: number;
                    /**
                     * @description 用戶的 ID。
                     * @example 1
                     */
                    user: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** @example 1 */
                                id?: number;
                                /** @example Super Admin */
                                name?: string;
                                /** @example superadmin */
                                username?: string;
                                /** @example admin */
                                role?: string;
                                /** @example 管理員 */
                                role_display?: string;
                                /** @example true */
                                is_admin?: boolean;
                                /** @example 2025-06-11T10:00:00.000000Z */
                                created_at?: string;
                                /** @example 2025-06-11T10:00:00.000000Z */
                                updated_at?: string;
                            };
                        };
                    };
                };
            };
        };
        /**
         * 更新指定用戶
         * @description 接收用戶更新請求，進行驗證後更新用戶資料。
         *     支援部分更新（只更新提供的欄位）。
         *     如果請求中包含密碼，會自動進行 bcrypt 雜湊處理。
         *     權限檢查：需要通過 UserPolicy::update() 方法（僅管理員可執行）
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The ID of the user.
                     * @example 17
                     */
                    id: number;
                    /**
                     * @description 用戶的 ID。
                     * @example 1
                     */
                    user: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 用戶姓名（可選更新）. Must not be greater than 255 characters.
                         * @example John Doe
                         */
                        name: string;
                        /**
                         * @description 用戶帳號（可選更新）. Must not be greater than 255 characters.
                         * @example johndoe
                         */
                        username: string;
                        /**
                         * @description 用戶密碼（可選更新，如不提供則保持原密碼）. Must be at least 8 characters.
                         * @example newpassword123
                         */
                        password?: string;
                        /**
                         * @description 用戶角色（可選更新）.
                         * @example admin
                         * @enum {string}
                         */
                        role: "admin" | "viewer";
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** @example 1 */
                                id?: number;
                                /** @example Super Admin */
                                name?: string;
                                /** @example superadmin */
                                username?: string;
                                /** @example admin */
                                role?: string;
                                /** @example 管理員 */
                                role_display?: string;
                                /** @example true */
                                is_admin?: boolean;
                                /** @example 2025-06-11T10:00:00.000000Z */
                                created_at?: string;
                                /** @example 2025-06-11T10:00:00.000000Z */
                                updated_at?: string;
                            };
                        };
                    };
                };
            };
        };
        post?: never;
        /**
         * 刪除指定用戶
         * @description 執行用戶刪除操作，成功後返回 204 No Content 回應。
         *     權限檢查：需要通過 UserPolicy::delete() 方法
         *
         *     安全機制：
         *     - 只有管理員可以刪除用戶
         *     - 管理員不能刪除自己的帳號（在 UserPolicy 中檢查）
         *     - 檢視者無法執行刪除操作
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description The ID of the user.
                     * @example 17
                     */
                    id: number;
                    /**
                     * @description 用戶的 ID。
                     * @example 1
                     */
                    user: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 處理使用者登入請求 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 使用者名稱
                         * @example superadmin
                         */
                        username: string;
                        /**
                         * @description 密碼
                         * @example password
                         */
                        password: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: {
                                /** @example 1 */
                                id?: number;
                                /** @example Super Admin */
                                name?: string;
                                /** @example superadmin */
                                username?: string;
                                /** @example admin */
                                role?: string;
                                /** @example 管理員 */
                                role_display?: string;
                                /** @example true */
                                is_admin?: boolean;
                                /** @example 2024-01-01T00:00:00.000000Z */
                                created_at?: string;
                                /** @example 2024-01-01T00:00:00.000000Z */
                                updated_at?: string;
                            };
                            /** @example 1|abcdefghijklmnopqrstuvwxyz */
                            token?: string;
                        };
                    };
                };
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example The given data was invalid. */
                            message?: string;
                            errors?: {
                                /** @example [
                                 *       "您提供的憑證不正確。"
                                 *     ] */
                                username?: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 處理使用者登出請求 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功登出 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    storeANewlyCreatedResourceInStorage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 1 */
                        id?: number;
                        /** @example PO-20240101-001 */
                        order_number?: string;
                        /** @example 150 */
                        total_amount?: number;
                        /** @example pending */
                        status?: string;
                        /** @example 2024-01-01T00:00:00+08:00 */
                        purchased_at?: string;
                        /** @example [] */
                        items?: unknown[];
                    };
                };
            };
        };
    };
    deleteApiStoresId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID of the store.
                 * @example 17
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    SPUSKU: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description SPU 的名稱。
                     * @example "經典棉質T-shirt"
                     */
                    name: string;
                    /**
                     * @description SPU 的描述。
                     * @example "100% 純棉"
                     */
                    description?: string | null;
                    /**
                     * @description 分類ID。
                     * @example 1
                     */
                    category_id?: number | null;
                    /**
                     * @description 該 SPU 擁有的屬性 ID 陣列。
                     * @example [
                     *       1,
                     *       2
                     *     ]
                     */
                    attributes: number[];
                    /**
                     * @description SKU 變體陣列，至少需要一項。
                     * @example [
                     *       []
                     *     ]
                     */
                    variants: {
                        /**
                         * @description 單一 SKU 變體的唯一庫存單位編號。. Must not be greater than 255 characters.
                         * @example HEADPHONE-BT-RED-L
                         */
                        sku: string;
                        /**
                         * @description 單一 SKU 變體的價格。. Must be at least 0.
                         * @example 199.99
                         */
                        price: number;
                        /**
                         * @description The <code>id</code> of an existing record in the attribute_values table.
                         * @example [
                         *       17
                         *     ]
                         */
                        attribute_value_ids?: number[];
                        /** @example {
                         *       "sku": "\"TSHIRT-RED-S\""
                         *     } */
                        "*"?: {
                            /**
                             * @description SKU 的唯一編號。
                             * @example "TSHIRT-RED-S"
                             */
                            sku: string;
                            /**
                             * @description SKU 的價格。
                             * @example 299.99
                             */
                            price: number;
                            /**
                             * @description 組成此 SKU 的屬性值 ID 陣列。
                             * @example [
                             *       10,
                             *       25
                             *     ]
                             */
                            attribute_value_ids: number[];
                        };
                    }[];
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 1 */
                            id?: number;
                            /** @example 測試產品 */
                            name?: string;
                            /** @example 這是一個測試產品的描述 */
                            description?: string;
                            /** @example TEST-SKU-001 */
                            sku?: string;
                            /** @example 199.99 */
                            price?: number;
                            /** @example 99.99 */
                            cost?: number;
                            /** @example 50 */
                            quantity?: number;
                            /** @example 1 */
                            category_id?: number;
                            /** @example 2023-10-15T08:30:45.000000Z */
                            created_at?: string;
                            /** @example 2023-10-15T08:30:45.000000Z */
                            updated_at?: string;
                            category?: {
                                /** @example 1 */
                                id?: number;
                                /** @example 電子產品 */
                                name?: string;
                                /** @example 各類電子產品 */
                                description?: string;
                                /** @example 2023-10-15T08:30:45.000000Z */
                                created_at?: string;
                                /** @example 2023-10-15T08:30:45.000000Z */
                                updated_at?: string;
                            };
                            /** @example [
                             *       {
                             *         "id": 1,
                             *         "name": "顏色",
                             *         "value": "黑色"
                             *       },
                             *       {
                             *         "id": 2,
                             *         "name": "尺寸",
                             *         "value": "中號"
                             *       }
                             *     ] */
                            attributes?: {
                                /** @example 1 */
                                id?: number;
                                /** @example 顏色 */
                                name?: string;
                                /** @example 黑色 */
                                value?: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
}
